import type { Config } from 'tailwindcss';
// Tailwind v3 theme extension. For Tailwind v4 use theme.v4.css instead.
const size = (px: number) => `calc(var(--mc-fs, 14px) * ${(px / 14).toFixed(4)})`;
export default {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        mc: {
          'page': 'var(--mc-page)',
          'surface': 'var(--mc-surface)',
          'panel': 'var(--mc-panel)',
          'panel-hover': 'var(--mc-panel-hover)',
          'row-hover': 'var(--mc-row-hover)',
          'control-hover': 'var(--mc-control-hover)',
          'skeleton': 'var(--mc-skeleton)',
          'line': 'var(--mc-line)',
          'line-soft': 'var(--mc-line-soft)',
          'line-table': 'var(--mc-line-table)',
          'line-notice': 'var(--mc-line-notice)',
          'line-strong': 'var(--mc-line-strong)',
          'line-control': 'var(--mc-line-control)',
          'line-missing': 'var(--mc-line-missing)',
          'ink': 'var(--mc-ink)',
          'ink-secondary': 'var(--mc-ink-secondary)',
          'ink-muted': 'var(--mc-ink-muted)',
          'accent': 'var(--mc-accent)',
          'accent-hover': 'var(--mc-accent-hover)',
          'accent-deep': 'var(--mc-accent-deep)',
          'accent-ink': 'var(--mc-accent-ink)',
          'accent-tint': 'var(--mc-accent-tint)',
          'accent-on': 'var(--mc-accent-on)',
          'notice': 'var(--mc-notice)',
          'error': 'var(--mc-error)',
          'error-bg': 'var(--mc-error-bg)',
        },
      },
      fontFamily: { sans: ['var(--mc-font-sans)'], mono: ['var(--mc-font-mono)'] },
      fontSize: {
        'mc-11': size(11),
        'mc-12': size(12),
        'mc-13': size(13),
        'mc-14': size(14),
        'mc-15': size(15),
        'mc-16': size(16),
        'mc-17': size(17),
        'mc-18': size(18),
        'mc-20': size(20),
        'mc-22': size(22),
        'mc-24': size(24),
        'mc-28': size(28),
      },
      borderRadius: { chip: '3px', btn: '4px', card: '6px', panel: '8px', sheet: '12px' },
      maxWidth: { run: '760px', queue: '1120px' },
      height: { header: '44px' },
      width: { rail: '248px' },
    },
  },
} satisfies Config;
